const KEY='medilog.state.v1';
let state=load();
const $=id=>document.getElementById(id);
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const pd=s=>s?new Date(`${s}T12:00:00`):null;
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const add=(s,n)=>{const d=pd(s);if(!d)return null;d.setDate(d.getDate()+Number(n||0));return iso(d)};
const diff=(a,b)=>Math.round((pd(b)-pd(a))/86400000);
const fmt=s=>s?pd(s).toLocaleDateString('zh-CN',{month:'short',day:'numeric'}):'—';
const fmtY=s=>s?pd(s).toLocaleDateString('zh-CN',{year:'numeric',month:'short',day:'numeric'}):'—';
const num=n=>Number(n||0).toLocaleString('zh-CN',{maximumFractionDigits:1});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&Array.isArray(x.medications)&&Array.isArray(x.events)?x:{version:1,medications:[],events:[]}}catch{return{version:1,medications:[],events:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function med(id){return state.medications.find(m=>m.id===id)}
function doseDates(m){const a=state.events.filter(e=>e.medicationId===m.id&&e.type==='dose').map(e=>e.date);if(m.seedDate)a.push(m.seedDate);return [...new Set(a)].sort()}
function lastDose(m){const a=doseDates(m);return a.length?a[a.length-1]:null}
function nextDose(m){const l=lastDose(m);return l?add(l,m.intervalDays):null}
function avgInterval(m){const a=doseDates(m);if(a.length<2)return null;const ds=a.slice(1).map((x,i)=>diff(a[i],x));return ds.reduce((x,y)=>x+y,0)/ds.length}
function sortedEvents(){return [...state.events].sort((a,b)=>b.date.localeCompare(a.date)||String(b.createdAt||'').localeCompare(String(a.createdAt||'')))}
function nearestMed(){let out=null;for(const m of state.medications){const n=nextDose(m);if(!n)continue;if(!out||pd(n)<pd(out.date))out={m,date:n}}return out}
function dueText(d){if(!d)return '未设置';const n=diff(today(),d);if(n===0)return '今天';if(n>0)return `${n} 天后`;return `已过 ${Math.abs(n)} 天`}
function stockStatus(m){if(Number(m.stock)<=0)return['库存为 0','empty'];if(Number(m.stock)<=Number(m.lowStock||0))return['库存偏低','low'];const uses=m.doseQty>0?Math.floor(Number(m.stock)/Number(m.doseQty)):0;return[`约 ${uses} 次用量`,'']}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
function render(){renderHero();renderMeds();renderHistory()}
function renderHero(){const x=nearestMed();if(!x){$('hero').innerHTML=`<div class="next-label">下一次预计用药</div><div class="next-main"><div class="next-copy"><div class="next-count">还没有计划</div><div class="next-meta">添加第一种药物和最近一次用药日期后自动计算</div></div><div class="stockchip"><strong>${state.medications.length}</strong><span>种药物</span></div></div><div class="hero-actions"><button class="hero-btn primary" id="heroAdd">添加药物</button><button class="hero-btn secondary" disabled>设提醒</button></div>`;$('heroAdd').onclick=()=>openMed();$('summary').innerHTML='';return}
const m=x.m;const last=lastDose(m),avg=avgInterval(m);$('hero').innerHTML=`<div class="next-label">下一次预计用药 · ${esc(m.name)}</div><div class="next-main"><div class="next-copy"><div class="next-count">${esc(dueText(x.date))}</div><div class="next-meta">${esc(fmtY(x.date))} · 计划每 ${num(m.intervalDays)} 天</div></div><div class="stockchip"><strong>${num(m.stock)}</strong><span>剩余 ${esc(m.unit)}</span></div></div><div class="hero-actions"><button class="hero-btn primary" id="heroDose">记录这次用药</button><button class="hero-btn secondary" id="heroReminder">设提醒</button></div>`;
$('heroDose').onclick=()=>openDose(m.id);$('heroReminder').onclick=()=>openReminder(m.id);
$('summary').innerHTML=`<div class="summary-card"><div class="summary-label">上次用药</div><div class="summary-value">${fmt(last)}</div></div><div class="summary-card"><div class="summary-label">实际平均间隔</div><div class="summary-value">${avg?`${num(avg)} 天`:'—'}</div></div><div class="summary-card"><div class="summary-label">剩余库存</div><div class="summary-value">${num(m.stock)} ${esc(m.unit)}</div></div>`}
function renderMeds(){const box=$('medList');if(!state.medications.length){box.innerHTML=`<div class="empty"><div class="empty-icon">✚</div><h3>先添加第一种药物</h3><p>可以从达必妥开始。以后也能继续记录其他注射药、片剂、吸入剂或补充剂。</p><button class="btn primary" id="emptyAdd">添加药物</button></div>`;$('emptyAdd').onclick=()=>openMed();return}
box.innerHTML=state.medications.map(m=>{const st=stockStatus(m),last=lastDose(m),next=nextDose(m);return `<article class="med-card"><div class="med-head"><div class="med-left"><div class="med-icon">${m.formType?.includes('注射')||m.formType?.includes('针')?'💉':'💊'}</div><div><div class="med-name">${esc(m.name)}</div><div class="med-meta">${esc(m.formType||'药物')} · 每 ${num(m.intervalDays)} 天</div></div></div><span class="status ${st[1]}">${esc(st[0])}</span></div><div class="med-row"><div class="mini"><span>库存</span><strong>${num(m.stock)} ${esc(m.unit)}</strong></div><div class="mini"><span>上次</span><strong>${fmt(last)}</strong></div><div class="mini"><span>下次</span><strong>${fmt(next)}</strong></div></div><div class="med-actions"><button class="btn primary dose" data-id="${m.id}">记录用药</button><button class="btn soft restock" data-id="${m.id}">补库存</button><button class="btn edit" data-id="${m.id}">•••</button></div></article>`}).join('');
box.querySelectorAll('.dose').forEach(b=>b.onclick=()=>openDose(b.dataset.id));box.querySelectorAll('.restock').forEach(b=>b.onclick=()=>openRestock(b.dataset.id));box.querySelectorAll('.edit').forEach(b=>b.onclick=()=>openMed(b.dataset.id))}
function eventHtml(e){const m=med(e.medicationId);if(!m)return'';const dose=e.type==='dose';return `<div class="event"><div class="event-icon">${dose?'💉':'📦'}</div><div><div class="event-title">${esc(m.name)} · ${dose?'用药':'补充库存'}</div><div class="event-sub">${fmtY(e.date)}${e.note?` · ${esc(e.note)}`:''}</div></div><div class="event-qty">${dose?'−':'＋'}${num(e.qty)} ${esc(m.unit)}</div></div>`}
function renderHistory(){const a=sortedEvents();$('historyHead').style.display=a.length?'flex':'none';$('timeline').innerHTML=a.slice(0,4).map(eventHtml).join('');$('allTimeline').innerHTML=a.length?a.map(eventHtml).join(''):'<div class="hint">还没有任何记录。</div>'}
function openMed(id=null){const m=id?med(id):null;$('medTitle').textContent=m?'编辑药物':'添加药物';$('medId').value=m?.id||'';$('medName').value=m?.name||'';$('medType').value=m?.formType||'注射笔';$('medUnit').value=m?.unit||'支';$('medStock').value=m?.stock??0;$('medDose').value=m?.doseQty??1;$('medInterval').value=m?.intervalDays??14;$('medLow').value=m?.lowStock??2;$('medSeed').value=m?.seedDate||'';$('medNotes').value=m?.notes||'';$('seedWrap').style.display=m?'none':'block';$('deleteBtn').style.display=m?'block':'none';$('deleteBtn').onclick=()=>removeMed(m?.id);$('medDialog').showModal()}
function openDose(id){const m=med(id);if(!m)return;$('doseMedId').value=id;$('doseName').value=m.name;$('doseDate').value=today();$('doseQty').value=m.doseQty;$('doseNote').value='';$('doseHint').textContent=`当前库存：${num(m.stock)} ${m.unit}。确认后会自动扣减。`;$('doseDialog').showModal()}
function openRestock(id){const m=med(id);if(!m)return;$('restockMedId').value=id;$('restockName').value=m.name;$('restockDate').value=today();$('restockQty').value=1;$('restockNote').value='';$('restockDialog').showModal()}
function openReminder(id){const m=med(id);if(!m)return;const n=nextDose(m);if(!n){toast('先记录最近一次用药日期');return}$('reminderMedId').value=id;$('reminderTitle').textContent=`${m.name} · ${fmtY(n)}`;$('reminderDialog').showModal()}
function removeMed(id){const m=med(id);if(!m||!confirm(`确定删除“${m.name}”以及它的全部历史记录吗？`))return;state.medications=state.medications.filter(x=>x.id!==id);state.events=state.events.filter(e=>e.medicationId!==id);save();$('medDialog').close();render();toast('已删除药物')}
$('medForm').addEventListener('submit',e=>{e.preventDefault();const id=$('medId').value;const data={name:$('medName').value.trim(),formType:$('medType').value,unit:$('medUnit').value.trim()||'份',stock:Number($('medStock').value),doseQty:Number($('medDose').value),intervalDays:Number($('medInterval').value),lowStock:Number($('medLow').value||0),notes:$('medNotes').value.trim()};if(!data.name||data.stock<0||data.doseQty<=0||data.intervalDays<=0)return;if(id){Object.assign(med(id),data,{updatedAt:new Date().toISOString()})}else{state.medications.push({id:uid(),...data,seedDate:$('medSeed').value||null,createdAt:new Date().toISOString()})}save();$('medDialog').close();render();toast(id?'已更新':'已添加')});
$('doseForm').addEventListener('submit',e=>{e.preventDefault();const m=med($('doseMedId').value),qty=Number($('doseQty').value),date=$('doseDate').value;if(!m||!date||qty<=0)return;if(qty>Number(m.stock)){toast('库存不足，请先补库存');return}m.stock=Math.max(0,Number(m.stock)-qty);state.events.push({id:uid(),type:'dose',medicationId:m.id,date,qty,note:$('doseNote').value.trim(),stockAfter:m.stock,createdAt:new Date().toISOString()});save();$('doseDialog').close();render();toast('用药已记录')});
$('restockForm').addEventListener('submit',e=>{e.preventDefault();const m=med($('restockMedId').value),qty=Number($('restockQty').value),date=$('restockDate').value;if(!m||!date||qty<=0)return;m.stock=Number(m.stock)+qty;state.events.push({id:uid(),type:'restock',medicationId:m.id,date,qty,note:$('restockNote').value.trim(),stockAfter:m.stock,createdAt:new Date().toISOString()});save();$('restockDialog').close();render();toast('库存已更新')});
function icsDate(s){return s.replaceAll('-','')}
function exportReminder(){const m=med($('reminderMedId').value);if(!m)return;const n=nextDose(m);if(!n)return;const before=Number($('reminderBefore').value||0),end=add(n,1);const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//MediLog//Medication Reminder//ZH','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:${uid()}@medilog`,`DTSTAMP:${stamp}`,`DTSTART;VALUE=DATE:${icsDate(n)}`,`DTEND;VALUE=DATE:${icsDate(end)}`,`SUMMARY:${m.name} 用药提醒`,`DESCRIPTION:MediLog 记录：计划每 ${m.intervalDays} 天。`,'BEGIN:VALARM','ACTION:DISPLAY',`TRIGGER:-P${before}D`,`DESCRIPTION:${m.name} 用药提醒`,'END:VALARM','END:VEVENT','END:VCALENDAR'];const blob=new Blob([lines.join('\r\n')],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`medilog-${m.name}-${n}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('reminderDialog').close();toast('日历提醒已生成')}
$('reminderExport').onclick=exportReminder;
$('addTop').onclick=()=>openMed();$('addBtn').onclick=()=>openMed();$('settingsBtn').onclick=()=>$('settingsDialog').showModal();$('allHistoryBtn').onclick=()=>$('historyDialog').showModal();
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({app:'MediLog',exportedAt:new Date().toISOString(),data:state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`medilog-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('备份已导出')};
$('importBtn').onclick=()=>$('importFile').click();$('importFile').addEventListener('change',async()=>{const f=$('importFile').files[0];if(!f)return;try{const p=JSON.parse(await f.text()),x=p.data||p;if(!Array.isArray(x.medications)||!Array.isArray(x.events))throw 0;if(!confirm('导入会覆盖当前设备上的 MediLog 数据，是否继续？'))return;state=x;save();render();$('settingsDialog').close();toast('备份已导入')}catch{toast('无法读取这个备份文件')}$('importFile').value=''});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();